openapi: 3.0.0
info:
  license:
    name: MIT
    url: https://raw.githubusercontent.com/libratbag/ratbag-emu/master/LICENSE
  title: ratbag-emu
  version: 0.0.1
servers:
- url: http://localhost:8080
tags:
- description: Control interface for the simulated device
  name: device
paths:
  /devices:
    get:
      description: Provides the list of devices that are being currently simulated
        by ratbag-emu
      operationId: list_devices
      parameters: []
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Device'
                type: array
          description: OK
      summary: List of simulated devices
      tags:
      - device
      x-openapi-router-controller: ratbag_emu_server.controllers.device_controller
  /devices/add:
    get:
      description: Tells ratbag-emu to create a new simulated device
      operationId: add_device
      parameters: []
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Device'
                type: array
          description: OK
      summary: Creates a simulated device
      tags:
      - device
      x-openapi-router-controller: ratbag_emu_server.controllers.device_controller
  /devices/{device_id}:
    get:
      description: Returns one the of devices currently simulated by ratbag-emu
      operationId: get_device
      parameters:
      - description: ID of the device to return
        explode: false
        in: path
        name: device_id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
          description: OK
        404:
          description: Device not found
      summary: Returns a simulated device
      tags:
      - device
      x-openapi-router-controller: ratbag_emu_server.controllers.device_controller
  /devices/{device_id}/event:
    post:
      description: Send raw HID event data to the target device
      operationId: device_event
      parameters:
      - description: ID of the device to return
        explode: false
        in: path
        name: device_id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventData'
        description: Event data
        required: true
      responses:
        200:
          description: OK
        400:
          description: Error sending data to the device
        404:
          description: Device not found
      summary: Send an event to a simulated device
      tags:
      - device
      x-openapi-router-controller: ratbag_emu_server.controllers.device_controller
components:
  requestBodies:
    Device:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Device'
      description: Simulated device
      required: true
  schemas:
    Device:
      description: Simulated device
      example:
        name: name
        id: 0
      properties:
        id:
          format: int32
          type: integer
        name:
          type: string
      required:
      - id
      title: Device
      type: object
    EventData:
      description: Raw HID event data
      example:
        data:
        - 0
        - 0
      properties:
        data:
          items:
            type: integer
          type: array
      required:
      - data
      title: Event data
      type: object
