openapi: 3.0.0
servers:
  - url: 'http://localhost:8080'

info:
  version: 0.0.1
  title: ratbag-emu
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/libratbag/ratbag-emu/master/LICENSE'

tags:
  - name: device
    description: Control interface for the simulated device

paths:
  /devices:
    get:
      tags:
        - device
      summary: List of simulated devices
      description: 'Provides the list of devices that are being currently simulated by ratbag-emu'
      operationId: list_devices
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
  /devices/add:
    get:
      tags:
        - device
      summary: Creates a simulated device
      description: 'Tells ratbag-emu to create a new simulated device'
      operationId: add_device
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
  '/devices/{device_id}':
    get:
      tags:
        - device
      summary: Returns a simulated device
      description: 'Returns one the of devices currently simulated by ratbag-emu'
      operationId: get_device
      parameters:
        - name: device_id
          in: path
          description: ID of the device to return
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '404':
          description: Device not found
  '/devices/{device_id}/event':
    post:
      tags:
        - device
      summary: Send an event to a simulated device
      operationId: device_event
      description: 'Send raw HID event data to the target device'
      parameters:
        - name: device_id
          in: path
          description: ID of the device to return
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        description: Event data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventData'
      responses:
        '200':
          description: OK
        '400':
          description: Error sending data to the device
        '404':
          description: Device not found

components:
  requestBodies:
    Device:
      description: Simulated device
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Device'
  schemas:
    Device:
      title: Device
      description: Simulated device
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
    EventData:
      title: Event data
      description: Raw HID event data
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            type: integer
