openapi: 3.0.0
servers:
  - url: 'http://localhost:8080'

info:
  version: 0.0.1
  title: ratbag-emu
  license:
    name: MIT
    url: 'https://raw.githubusercontent.com/libratbag/ratbag-emu/master/LICENSE'

tags:
  - name: device
    description: Control interface for the simulated device

paths:
  /devices:
    get:
      tags:
        - device
      summary: List of simulated devices
      description: 'Provides the list of devices that are being currently simulated by ratbag-emu'
      operationId: ratbag_emu.server.list_devices
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
  '/devices/add':
    post:
      tags:
        - device
      summary: Creates a simulated device
      description: 'Tells ratbag-emu to create a new simulated device'
      operationId: ratbag_emu.server.add_device
      requestBody:
        description: Short name name of the device to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Device'
      responses:
        '200':
          description: OK
        '400':
          description: Can't add device
  '/devices/{device_id}':
    get:
      tags:
        - device
      summary: Returns a simulated device
      description: 'Returns one the of devices currently simulated by ratbag-emu'
      operationId: ratbag_emu.server.get_device
      parameters:
        - name: device_id
          in: path
          description: ID of the device to return
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '404':
          description: Device not found
    delete:
      tags:
        - device
      summary: Deletes a simulated device
      operationId: ratbag_emu.server.delete_device
      parameters:
        - name: device_id
          in: path
          description: ID of the device to delete
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: OK
        '404':
          description: Device not found
  '/devices/{device_id}/event':
    post:
      tags:
        - device
      summary: Send an event to a simulated device
      operationId: ratbag_emu.server.device_event
      description: 'Send HID event data to the target device'
      parameters:
        - name: device_id
          in: path
          description: ID of the device to use as the event source
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        description: Event data
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                additionalProperties:
                  type: integer
                  format: int32
      responses:
        '200':
          description: OK
        '400':
          description: Error sending data to the device
        '404':
          description: Device not found

components:
  schemas:
    Device:
      title: Device
      description: Simulated device
      type: object
      required:
        - shortname
      properties:
        id:
          type: integer
          format: int32
        shortname:
          type: string
        name:
          type: string
